### ISSUE TITLE
Bug when running  manage.py

### ISSUE THREAD

**Issue by LukasMeine** [quantifiedcode/quantifiedcode#11]
Ran installation just like in the documentation and got this error:
This project is amazing, keep up the good work!

Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from quantifiedcode.settings import settings
  File "/home/meine_joaolucas/quantifiedcode/quantifiedcode/settings/__init__.py", line 1, in <module>
    from .base import * #noqa
  File "/home/meine_joaolucas/quantifiedcode/quantifiedcode/settings/base.py", line 12, in <module>
    from quantifiedcode.helpers.settings import Settings, load_settings
  File "/home/meine_joaolucas/quantifiedcode/quantifiedcode/helpers/settings.py", line 13, in <module>
    from checkmate.settings import Settings as CheckmateSettings
ImportError: No module named checkmate.settings

**Comment by adewes** [comment]
Hey @LukasMeine , thanks for opening this issue! @marcinguy (who recently installed QuantifiedCode and may be able to help you) can you give some pointers here?
From looking at the traceback it seems that checkmate is not properly installed or not on the `PYTHONPATH`, you can check this by opening `python3` and importing the module `import checkmate.settings`.

**Comment by ghost** [comment]
@LukasMeine did you install checkmate module? After you clone the checkmate module, please run `python setup.py install` in the cloned folder to install checkmate system-wide. I think than it should work. Let me know.

**Comment by ghost** [comment]
@LukasMeine did u resolve it? U can try it again (checkmate was updated to newer dependencies in my fork). There is also graph based LLM code review checker. Feel free to take a look at the repo for more info

**Comment by ghost** [comment]
Here are the repos:

https://github.com/tcosolutions/betterscan

https://github.com/tcosolutions/checkmate5

https://github.com/tcosolutions/aigraphcodescan
