### ISSUE TITLE
no settings.yml file

### ISSUE THREAD

**Issue by brycekallen** [quantifiedcode/quantifiedcode#3]
It looks like in .gitignore you have ignored the settings.yml file which is necessary for the `python manage.py setup` step. Any way this can be added back?

Thanks

**Comment by adewes** [comment]
Hey Bryce, can you try to create an empty `settings.yml` and then run `python manage.py setup` (which should create the correct entries)?

Sorry the installer is still very rough around the edges and I'm working on a better one as well as a Docker version, I will update you as soon as those are online.

**Comment by brycekallen** [comment]
@adewes Thanks for getting back to me. Its funny I tried that exact fix before raising the issue and still got an error:
```
ballen:quantifiedcode ballen$ touch settings.yml
ballen:quantifiedcode ballen$ python manage.py setup
Loading settings from /Users/ballen/quantifiedcode/quantifiedcode/settings/default.yml
Loading settings from /Users/ballen/quantifiedcode/settings.yml
Traceback (most recent call last):
  File "manage.py", line 2, in <module>
    from quantifiedcode.backend.commands import commands
  File "/Users/ballen/quantifiedcode/quantifiedcode/backend/commands/__init__.py", line 6, in <module>
    from .server import runserver
  File "/Users/ballen/quantifiedcode/quantifiedcode/backend/commands/server.py", line 2, in <module>
    from quantifiedcode.app import get_app
  File "/Users/ballen/quantifiedcode/quantifiedcode/app.py", line 21, in <module>
    from quantifiedcode.backend.app import get_app as get_backend_app
  File "/Users/ballen/quantifiedcode/quantifiedcode/backend/app.py", line 22, in <module>
    from .api.v1 import routes as routes_v1
  File "/Users/ballen/quantifiedcode/quantifiedcode/backend/api/v1/__init__.py", line 1, in <module>
    from .routes import routes
  File "/Users/ballen/quantifiedcode/quantifiedcode/backend/api/v1/routes.py", line 51, in <module>
    from .issue import (
  File "/Users/ballen/quantifiedcode/quantifiedcode/backend/api/v1/issue.py", line 18, in <module>
    from .forms.issue_status import IssueStatusForm
  File "/Users/ballen/quantifiedcode/quantifiedcode/backend/api/v1/forms/issue_status.py", line 6, in <module>
    class IssueStatusForm(Form):
  File "/Users/ballen/quantifiedcode/quantifiedcode/backend/api/v1/forms/issue_status.py", line 9, in IssueStatusForm
    ignore_reason = SelectField(u"Ignore Reason", choices=[(str(Issue.IgnoreReason.false_positive),"false positive"),
AttributeError: type object 'Issue' has no attribute 'IgnoreReason'
```
At that point I just figured I'd reach out to see if it was worth proceeding further

**Comment by adewes** [comment]
Ah okay this might be an issue with the checkmate version, please do not invest more time in this (as I think it needs to be resolved on our side) and let me get back to you as soon as I have the installer ready.

**Comment by IBestuzhev** [comment]
I had the same issue - installing `checkmate` from GitHub instead of pypi helped with this traceback.  
BTW, it was not added to `requirements.txt` and neither described in readme.

Later it fails with blank `settings.yml` file. I had to put `backend: {}` there for commands to start. However setup did not modify the file, so I had to put DB and Rabbit URLs manually

**Comment by wolfy1339** [comment]
This issue is very well still present

**Comment by jrial** [comment]
Could you please add a sample file so we know what kind of settings can be defined, and what the structure looks like?

Writing a better installer takes time (as evidenced by the fact that this issue is now open for over six weeks), while a sample file is something you can literally sanitise from your local settings file and commit in 5-10 minutes.

**Comment by adewes** [comment]
Hi @jrial and @wolfy1339, sorry I was very busy in the last week, I'll add/fix the install instructions and the problems with the settings file as soon as possible.

**Comment by wolfy1339** [comment]
Here's the default config: https://github.com/quantifiedcode/quantifiedcode/blob/master/quantifiedcode/settings/default.yml

**Comment by jrial** [comment]
@wolfy1339 thanks, I've found that one as well in the meantime, while looking at the setup procedure.

Onto the next problem: Celery! ;)

**Comment by adewes** [comment]
Thanks for helping with this, I'm working on a Python-3 compatible version that should solve the current issues and hope to release it this weekend!

**Comment by adewes** [comment]
@jrial you should be able to switch to Celery 4 (in the requirements) now as they finally fixed the upstream bug which prevented this. I'll also upgrade that in the new release.

**Comment by haoshenzhang** [comment]
@wolfy1339 when I analyze an project I got  http 404 error the ression is that I coun't get snapshot
