### ISSUE TITLE
Error when I try to add a new git repo

### ISSUE THREAD

**Issue by IBestuzhev** [quantifiedcode/quantifiedcode#4]
When I try to add the first one repo - I had the following error:

```
172.22.0.1 - - [16/Aug/2017 08:43:03] "POST /api/v1/project/git HTTP/1.1" 500 -
global name 'DuplicateProject' is not defined
Traceback (most recent call last):
  File "/opt/project/quantifiedcode/backend/api/resource.py", line 129, in handle
    handler_response = handler(*args, **kwargs)
  File "/opt/project/quantifiedcode/backend/decorators.py", line 378, in decorated_function
    return f(*args, **kwargs)
  File "/opt/project/quantifiedcode/plugins/git/backend/api/v1/resources/project.py", line 84, in post
    except DuplicateProject:
NameError: global name 'DuplicateProject' is not defined
```

I installed all packages via `pip install -r requirements.txt` and additionally I installed `checkmate` from github - `git+https://github.com/quantifiedcode/checkmate.git`

**Comment by adewes** [comment]
Thanks for reporting this, I'm working on a fully functioning installer and will let you now as soon as it's ready!
