### ISSUE TITLE
I got this issues wen I When I analyze an project by quantifiedcode

### ISSUE THREAD

**Issue by haoshenzhang** [quantifiedcode/quantifiedcode#8]
Replacing class <class 'checkmate.lib.models.IssueClass'> with <class 'quantifiedcode.backend.models.issue_class.IssueClass'> for collection issueclass
Replacing class <class 'checkmate.lib.models.Project'> with <class 'quantifiedcode.backend.models.project.Project'> for collection project
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [12/Oct/2017 10:24:24] "GET /api/v1/settings HTTP/1.1" 200 -
127.0.0.1 - - [12/Oct/2017 10:24:25] "GET /api/v1/projects?sort=analyzed_at&direction=desc HTTP/1.1" 200 -
127.0.0.1 - - [12/Oct/2017 10:24:25] "GET /api/v1/user? HTTP/1.1" 200 -
127.0.0.1 - - [12/Oct/2017 10:24:27] "GET /api/v1/settings HTTP/1.1" 304 -
127.0.0.1 - - [12/Oct/2017 10:24:28] "GET /api/v1/project/6011df4479054f2a87de1c448b3c1b4c?with_branches=true HTTP/1.1" 200 -
127.0.0.1 - - [12/Oct/2017 10:24:28] "GET /api/v1/project/6011df4479054f2a87de1c448b3c1b4c? HTTP/1.1" 200 -
127.0.0.1 - - [12/Oct/2017 10:24:30] "GET /api/v1/project/6011df4479054f2a87de1c448b3c1b4c/snapshot/:HEAD? HTTP/1.1" 404 -
127.0.0.1 - - [12/Oct/2017 10:24:31] "GET /api/v1/project/6011df4479054f2a87de1c448b3c1b4c/snapshot/:HEAD/issues_summary? HTTP/1.1" 404 -

**Comment by jlebonzec** [comment]
Hello!

I think it is related to this celery exception:
```
SchedulingError: Couldn't apply scheduled task analyze-projects: 'NoneType' object is not callable
Message Error: Couldn't apply scheduled task analyze-projects: 'NoneType' object is not callable
['  File "/opt/quantifiedcode/manage.py", line 22, in <module>\n    qc()\n', '  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__\n    return self.main(*args, **kwargs)\n', '  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main\n    rv = self.invoke(ctx)\n', '  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n', '  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n', '  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke\n    return callback(*args, **kwargs)\n', '  File "/opt/quantifiedcode/quantifiedcode/backend/commands/celery.py", line 14, in runworker\n    celery.worker_main(argv)\n', '  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 206, in worker_main\n    app=self).execute_from_commandline(argv)\n', '  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 311, in execute_from_commandline\n    return self.handle_argv(self.prog_name, argv[1:])\n', '  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 377, in handle_argv\n    return self(*args, **options)\n', '  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 274, in __call__\n    ret = self.run(*args, **kwargs)\n', '  File "/usr/local/lib/python2.7/dist-packages/celery/bin/worker.py", line 212, in run\n    state_db=self.node_format(state_db, hostname), **kwargs\n', '  File "/usr/local/lib/python2.7/dist-packages/celery/worker/__init__.py", line 206, in start\n    self.blueprint.start(self)\n', '  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start\n    step.start(parent)\n', '  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 374, in start\n    return self.obj.start()\n', '  File "/usr/local/lib/python2.7/dist-packages/billiard/process.py", line 137, in start\n    self._popen = Popen(self)\n', '  File "/usr/local/lib/python2.7/dist-packages/billiard/forking.py", line 105, in __init__\n    code = process_obj._bootstrap()\n', '  File "/usr/local/lib/python2.7/dist-packages/billiard/process.py", line 292, in _bootstrap\n    self.run()\n', '  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 553, in run\n    self.service.start(embedded_process=True)\n', '  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 479, in start\n    interval = self.scheduler.tick()\n', '  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 221, in tick\n    next_time_to_run = self.maybe_due(entry, self.publisher)\n', '  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 207, in maybe_due\n    exc, traceback.format_stack(), exc_info=True)\n']
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 204, in maybe_due
    result = self.apply_async(entry, publisher=publisher)
  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 260, in apply_async
    entry, exc=exc)), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 252, in apply_async
    **entry.options)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 573, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "/usr/local/lib/python2.7/dist-packages/celery/app/amqp.py", line 310, in publish_task
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 449, in _ensured
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 177, in _publish
    channel = self.channel
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 194, in _get_channel
    channel = self._channel = channel()
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 425, in __call__
    value = self.__value__ = self.__contract__()
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 209, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 773, in default_channel
    self._default_channel = self.channel()
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 255, in channel
    chan = self.transport.create_channel(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/pyamqp.py", line 92, in create_channel
    return connection.channel()
  File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 462, in channel
    channel.open()
  File "/usr/local/lib/python2.7/dist-packages/amqp/channel.py", line 434, in open
    spec.Channel.Open, 's', ('',), wait=spec.Channel.OpenOk,
  File "/usr/local/lib/python2.7/dist-packages/amqp/abstract_channel.py", line 50, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
SchedulingError: Couldn't apply scheduled task analyze-projects: 'NoneType' object is not callable
```

I am currently investigating, but if @adewes has any immediate feedback, that would save time. :)

**Comment by jlebonzec** [comment]
Sorry, it actually looks like the previous error was due do the version of rabbitmq used. I moved to redis and I now get this stacktrace.
```
Task quantifiedcode.backend.tasks.periodic.analyze_pending_project[70d9cab0-19d9-45a9-ba17-dda23863d912] raised unexpected: IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/quantifiedcode/quantifiedcode/backend/tasks/periodic.py", line 87, in analyze_pending_project
    analyze_project(pending_project.pk, task_id=analyze_pending_project.request.id)
  File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 428, in __call__
    return self.run(*args, **kwargs)
  File "/opt/quantifiedcode/quantifiedcode/backend/tasks/project/analyze.py", line 69, in analyze_project
    with TaskLogger(analysis_task, backend=backend, ping=True):
  File "/opt/quantifiedcode/quantifiedcode/backend/tasks/helpers.py", line 80, in __enter__
    self.task_logger = TaskPingHandler(self.backend, self.task, **kwargs)
  File "/opt/quantifiedcode/quantifiedcode/backend/tasks/helpers.py", line 48, in __init__
    super(TaskPingHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 945, in _open
    stream = codecs.open(self.baseFilename, self.mode, self.encoding)
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/opt/quantifiedcode/quantifiedcode/backend/data/tasks/40b95c57611f4f87b929dc4dbc764945.log'
```

Some logs seem to not be accessible? I'm continuing my investigations.

**Comment by jlebonzec** [comment]
Putting `project_path` instead of `backend.path` here solved the log problem for me:
https://github.com/quantifiedcode/quantifiedcode/blob/master/quantifiedcode/backend/tasks/helpers.py#L73

Also, in the default config, it seems that this line should say `git_repositories`:
https://github.com/quantifiedcode/quantifiedcode/blob/master/quantifiedcode/settings/default.yml#L7

**Comment by hfa0** [comment]
Same issue for me 
```127.0.0.1 - - [29/Apr/2019 11:02:46] "GET /api/v1/user HTTP/1.1" 304 -
127.0.0.1 - - [29/Apr/2019 11:02:57] "GET /api/v1/project/be306d6f64e64040978ff68256ed74c0/snapshot/:HEAD HTTP/1.1" 404 -
127.0.0.1 - - [29/Apr/2019 11:02:57] "GET /api/v1/project/be306d6f64e64040978ff68256ed74c0/issues_data HTTP/1.1" 304 -
127.0.0.1 - - [29/Apr/2019 11:02:57] "GET /api/v1/project/be306d6f64e64040978ff68256ed74c0/snapshot/:HEAD/issues_summary HTTP/1.1" 404 -
127.0.0.1 - - [29/Apr/2019 11:02:57] "GET /api/v1/user HTTP/1.1" 304 -
127.0.0.1 - - [29/Apr/2019 11:03:08] "GET /api/v1/project/be306d6f64e64040978ff68256ed74c0/snapshot/:HEAD HTTP/1.1" 404 -
127.0.0.1 - - [29/Apr/2019 11:03:08] "GET /api/v1/project/be306d6f64e64040978ff68256ed74c0/snapshot/:HEAD/issues_summary HTTP/1.1" 404 -
127.0.0.1 - - [29/Apr/2019 11:03:08] "GET /api/v1/project/be306d6f64e64040978ff68256ed74c0/issues_data HTTP/1.1" 304 -
127.0.0.1 - - [29/Apr/2019 11:03:08] "GET /api/v1/user HTTP/1.1" 304

already tried out the above-mentioned fix.
