### ISSUE TITLE
Error launching setup.

### ISSUE THREAD

**Issue by TheTechOddBug** [quantifiedcode/quantifiedcode#9]
This is the error I obtain when I launch python manage.py setup:

`python manage.py setup
Traceback (most recent call last):
  File "manage.py", line 1, in <module>
    from quantifiedcode.settings import settings
  File "/home/josemariagutierrez/gitrepos/quantifiedcode/quantifiedcode/settings/__init__.py", line 1, in <module>
    from .base import * #noqa
  File "/home/josemariagutierrez/gitrepos/quantifiedcode/quantifiedcode/settings/base.py", line 12, in <module>
    from quantifiedcode.helpers.settings import Settings, load_settings
  File "/home/josemariagutierrez/gitrepos/quantifiedcode/quantifiedcode/helpers/settings.py", line 13, in <module>
    from checkmate.settings import Settings as CheckmateSettings
ImportError: No module named checkmate.settings`

**Comment by amoursu** [comment]
https://github.com/quantifiedcode/quantifiedcode/issues/6

**Comment by azure1016** [comment]
Same here. I found checkmate.py in quantifidecode/backend/commands. And then I check the file, finding there no 'settings' at all. I guess some codes were removed accidentally? (I was running python 2.7.12)

**Comment by jrial** [comment]
`pip install -e git://github.com/quantifiedcode/checkmate.git#egg=checkmate` is your friend.
